# Generated by Django 5.0.2 on 2024-03-04 12:15

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_role', models.CharField(default='user')),
                ('ph_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile-pictures/')),
                ('client_code', models.CharField()),
                ('geographical_region', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=3)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
